### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Max-Marchenko9/kinozal-template#1]
1)
Нет скруглений по краям.
![image](https://user-images.githubusercontent.com/8464662/132626712-eaf89f98-a2c4-4ac0-89a7-0111e1708d10.png)

2)
Некорректный вид элемента.
![image](https://user-images.githubusercontent.com/8464662/132626826-78d57236-af87-46dc-836a-7ae5ddb6adac.png)

3)
Некорректный вид элемента.
![image](https://user-images.githubusercontent.com/8464662/132626933-a727c32a-ddb1-4dcc-a5b1-de0fa3516570.png)
![image](https://user-images.githubusercontent.com/8464662/132626993-541459ca-d267-4338-a2e8-db45cdf5aa31.png)

**Comment by Max-Marchenko9** [comment]
https://max-marchenko9.github.io/kinozal-template/

исправил

чт, 9 сент. 2021 г. в 08:17, Andrey ***@***.***>:
